### ISSUE TITLE
Errors to fix - ssdp - pywemo

### ISSUE THREAD

**Issue by pavoni** [pavoni/home-assistant-custom-components#21]
15-11-30 00:29:01 pywemo.ssdp: Error fetching description at http://192.168.1.254:1780/WFADevice.xml
Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 135, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 90, in create_connection
    raise err
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 80, in create_connection
    sock.connect(sa)
socket.timeout: timed out

**Comment by pavoni** [comment]
Now handled.
